apiVersion: v2
name: cert-exporter
description: The cert-exporter walks a directory path it has gotten as input and emits all NotAfter timestamps as metrics.
version: [[.Version]]
appVersion: 2.9.16
home: https://github.com/giantswarm/cert-exporter
icon: https://s.giantswarm.io/app-icons/prometheus/1/light.svg
annotations:
  application.giantswarm.io/team: turtles
  ui.giantswarm.io/logo: https://s.giantswarm.io/app-icons/prometheus/1/light.svg
